<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     Option1  _bf898a</name>
   <tag></tag>
   <elementGuidId>bc4fad03-75c4-4d6f-8c40-f8c9820783cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown-class-example']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown-class-example</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dropdown-class-example</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b80e541-033a-4e65-956c-34c5e6bd2754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>fa7c06ac-2dc4-43c7-9f3c-fc39f03662c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>529e4caf-2caa-48ca-ac76-6a226772976d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Select
                     Option1
                    Option2
                    Option3
                </value>
      <webElementGuid>fe556fef-5bc7-4807-ad6f-cb6d65818a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-class-example&quot;)</value>
      <webElementGuid>d9ca4cbb-fbce-477d-b7a2-c566bbf1b7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown-class-example']</value>
      <webElementGuid>1f7e6497-903a-4a57-aac9-993e5d28b247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/following::select[1]</value>
      <webElementGuid>20d12ae9-7d58-402f-a7ea-45d656791b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggession Class Example'])[1]/following::select[1]</value>
      <webElementGuid>ae5067d2-2614-40f0-91e8-f4f17e468b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::select[1]</value>
      <webElementGuid>fb2722f0-2e2e-4d14-816c-141b6805f463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c3ca4161-2c9a-4326-ab86-3bc1bd7fd502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown-class-example' and @name = 'dropdown-class-example' and (text() = '
                     Select
                     Option1
                    Option2
                    Option3
                ' or . = '
                     Select
                     Option1
                    Option2
                    Option3
                ')]</value>
      <webElementGuid>992d1876-3c5f-4115-a67b-b65dca93e525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
