<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     Option1  _bf898a</name>
   <tag></tag>
   <elementGuidId>bc4fad03-75c4-4d6f-8c40-f8c9820783cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown-class-example']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown-class-example</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dropdown-class-example</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>783932c6-645d-4d18-8ce5-b1d52fc20a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>79859f98-340c-40c3-ab5e-02adb7c4d50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>30cf7c5d-e241-4e8a-b923-8947de60ad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Select
                     Option1
                    Option2
                    Option3
                </value>
      <webElementGuid>90e167e9-c89c-49ad-a856-a33234a4d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-class-example&quot;)</value>
      <webElementGuid>d76af6af-7427-4d6d-95cc-793431173840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown-class-example']</value>
      <webElementGuid>cb2c708c-339c-4aa6-a2ea-bc43ec1f2654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/following::select[1]</value>
      <webElementGuid>d1858fed-c42f-4ff7-8e9f-26c0f320db7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggession Class Example'])[1]/following::select[1]</value>
      <webElementGuid>324594ab-acd2-471b-a461-29e624455ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::select[1]</value>
      <webElementGuid>eca12e19-3f1b-49eb-a9a9-f0f9acf648cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>918167a0-5aea-4816-950d-d596de47bd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown-class-example' and @name = 'dropdown-class-example' and (text() = '
                     Select
                     Option1
                    Option2
                    Option3
                ' or . = '
                     Select
                     Option1
                    Option2
                    Option3
                ')]</value>
      <webElementGuid>140df220-b392-443a-a8a4-819c57c83d8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
