<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Receptionist</name>
   <tag></tag>
   <elementGuidId>de4aaaca-2c39-401b-b89d-c4ab52d23752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='product']/tbody/tr[4]/td[2])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tableFixHead > #product > tbody > tr:nth-of-type(4) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Receptionist&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>140aaebd-e384-4f8d-9231-c009c57d8130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Receptionist</value>
      <webElementGuid>a0d2c88f-be72-4336-850d-f3bcf3d8305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;block large-row-spacer&quot;]/div[@class=&quot;right-align&quot;]/fieldset[2]/div[@class=&quot;tableFixHead&quot;]/table[@id=&quot;product&quot;]/tbody[1]/tr[4]/td[2]</value>
      <webElementGuid>5424ca28-a06e-4006-8eb5-25b77b9139c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='product']/tbody/tr[4]/td[2])[2]</value>
      <webElementGuid>1f757721-f80f-4136-b9d1-d01e9c625efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ivory'])[1]/following::td[1]</value>
      <webElementGuid>6d9bb0f4-829a-4d41-b5bd-ca9c87cc2f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolkata'])[1]/following::td[3]</value>
      <webElementGuid>5f22e1fb-6b60-4f32-aecf-1dc7dae18b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[2]/preceding::td[1]</value>
      <webElementGuid>964a0c1d-f085-4f4a-8a26-bd916c33e14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jack'])[1]/preceding::td[3]</value>
      <webElementGuid>1ec2a426-169f-4827-81f8-6e0489475b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Receptionist']/parent::*</value>
      <webElementGuid>252ba627-c96e-46e7-8147-c53479b66b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>2fe3bf11-26a5-4463-8b65-ceaeddd695ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Receptionist' or . = 'Receptionist')]</value>
      <webElementGuid>13c4c48e-9c1d-4a17-8295-df5b08fc41f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
